name: Reseed Database

on:
  schedule:
    - cron: '0 * * * *'  # every hour, on the hour
  workflow_dispatch:      # allow manual trigger from GitHub UI

jobs:
  reseed:
    name: Reseed on Fly.io
    runs-on: ubuntu-latest

    steps:
      - name: Set up flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Reseed database
        run: flyctl ssh console -a unpoly-contact-manager-demo -C "DISABLE_DATABASE_ENVIRONMENT_CHECK=1 bin/rails db:seed:replant"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
